<?php

/**
 * @file
 * Implements tpay.com Payments in Drupal Commerce checkout.
 */

/**
 * @return mixed
 */
function commerce_tpay_menu()
{
  $items['commerce_tpay/verify'] = array(
    'title' => 'Tpay callback transaction',
    'page callback' => 'commerce_tpay_verify',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'commerce_tpay.inc',
    'file path' => drupal_get_path('module', 'commerce_tpay') . '/includes',
  );

  return $items;
}

/**
 * @return array
 */
function commerce_tpay_commerce_payment_method_info()
{
  $payment_methods = array();

  $payment_methods['tpay'] = array(
    'method_id' => 'tpay',
    'base' => 'commerce_tpay',
    'title' => t('tpay.com <img src="@src" title="tpay.com" alt="tpay.com">', array('@src' => '/' . drupal_get_path('module', 'commerce_tpay') . '/img/tpay_logo.png')),
    'short_title' => t('tpay.com'),
    'description' => t('Payment with tpay.com'),
    'terminal' => FALSE,
    'offsite' => TRUE,
  );

  return $payment_methods;
}

/**
 * @param null $settings
 * @return array
 */
function commerce_tpay_settings_form($settings = NULL)
{
  $form = array();

  $settings = (array)$settings + array(
      'sid' => 0,
      'cod' => '',
      'ip' => '195.149.229.109,148.251.96.163,178.32.201.77,46.248.167.59,46.29.19.106'
    );

  $form['sid'] = array(
    '#title' => t('Seller ID'),
    '#type' => 'textfield',
    '#default_value' => $settings['sid'],
    '#description' => t('Required when stating new transaction variables.'),
    '#required' => TRUE,
  );

  $form['cod'] = array(
    '#title' => t('Authorized code'),
    '#type' => 'textfield',
    '#default_value' => $settings['cod'],
    '#description' => t('The same like in seller panel (Settings->Notifications->Authorized code).'),
  );
  $form['ip'] = array(
    '#title' => t('Server IP'),
    '#type' => 'textfield',
    '#default_value' => $settings['ip'],
    '#description' => t('Tpay server IP notification. Coma separated values.'),
  );

  return $form;
}

/**
 * @param $payment_method
 * @param $pane_values
 * @param $checkout_pane
 * @param $order
 * @return array
 */
function commerce_tpay_submit_form($payment_method, $pane_values, $checkout_pane, $order)
{
  if (empty($payment_method['settings']['sid']) ||
    empty($payment_method['settings']['ip'])) {
    drupal_set_message(t('tpay.com is not configured for use.'), 'error');
  }

  $form = array();

  if (!empty($order->data['commerce_payment_tpay'])) {
    $pane_values += $order->data['commerce_payment_tpay'];
  }

  return $form;
}

/**
 * @param $form
 * @param $form_state
 * @param $order
 * @param $payment_method
 * @return mixed
 */
function commerce_tpay_redirect_form($form, &$form_state, $order, $payment_method)
{
  global $language;

  $lang = in_array($language->language, array('pl', 'en', 'de')) ? $language->language : 'en';

  if (empty($payment_method['settings']['sid']) || empty($payment_method['settings']['ip'])) {
    drupal_set_message(t('tpay.com is not configured for use.'), 'error');
  }

  $wrapper = entity_metadata_wrapper('commerce_order', $order);

  $amount = $wrapper->commerce_order_total->amount->value();
  $crc = $order->order_id . ':' . $order->data['payment_redirect_key'];
  $sid = $payment_method['settings']['sid'];
  $pmid = $payment_method['settings']['cod'];
  $md5 = $sid . $amount / 100 . $crc . $pmid;

  $url_fail = "checkout/" . $order->order_id . "/payment/back/" . $order->data['payment_redirect_key'];
  $url_ok = "checkout/" . $order->order_id . "/payment/return/" . $order->data['payment_redirect_key'];

  $data = array(
    'id' => $payment_method['settings']['sid'],
    'kwota' => $amount / 100,
    'opis' => t('Order number @order_number in @store', array('@order_number' => $order->order_number, '@store' => variable_get('site_name', url('<front>', array('absolute' => TRUE))))),
    'crc' => $crc,
    'wyn_url' => url('commerce_tpay/verify', array('absolute' => TRUE)),
    'wyn_email' => variable_get('site_mail'),
    'pow_url' => url($url_ok, array('absolute' => TRUE)),
    'pow_url_blad' => url($url_fail, array('absolute' => TRUE)),
    'email' => $order->mail,
    'nazwisko' => '',
    'imie' => '',
    'adres' => '',
    'miasto' => '',
    'kod' => '',
    'kraj' => '',
    'telefon' => '',
    'jezyk' => $lang
  );

  $params_map = array(
    'nazwisko' => 'name_line',
    'adres' => 'thoroughfare',
    'miasto' => 'locality',
    'kod' => 'postal_code',
    'kraj' => 'country',
  );

  foreach ($params_map as $key => $value) {
    if (isset($wrapper->commerce_customer_billing->commerce_customer_address->$value)) {
      $data[$key] = $wrapper->commerce_customer_billing->commerce_customer_address->$value->value();
    }
  }

  $data['md5sum'] = md5($md5);

  $form['#action'] = 'https://secure.tpay.com';

  foreach ($data as $name => $value) {
    if (!empty($value)) {
      $form[$name] = array('#type' => 'hidden', '#value' => $value);
    }
  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Pay via tpay.com'),
  );

  return $form;
}
